import {Component, OnInit} from '@angular/core';
import {MatTabsModule} from '@angular/material/tabs';
import {MatCardModule} from '@angular/material/card';
import {MatListModule} from '@angular/material/list';
import {Memo} from '../../models/memo.model'
import {DatePipe} from '@angular/common';
import {MatIcon} from '@angular/material/icon';
import {MatToolbar} from '@angular/material/toolbar';
import {MatIconButton} from '@angular/material/button';

@Component({
  selector: 'app-inbox',
  imports: [
    MatTabsModule,
    MatCardModule,
    MatListModule,
    DatePipe,
    MatIcon,
    MatToolbar,
    MatIconButton,
  ],
  templateUrl: './inbox.component.html',
  styleUrl: './inbox.component.css'
})
export class InboxComponent implements OnInit {

  memos: Memo[] = [];
  selectedMemo: Memo | null = null;
  isListVisible: boolean = true;


  ngOnInit(): void {
    this.memos = memoMockData;
  }

  selectMemo(memo: Memo): void {
    this.selectedMemo = memo;
    this.isListVisible = !this.isListVisible;
  }

}

export const memoMockData: Memo[] = [
  {
    id: "memo1",
    sentBy: {
      id: 1,
      firstName: "John",
      lastName: "Doe",
      email: "john.doe@example.com",
      password: "placeholderPassword",
      department: { id: 1, name: "General" },
      position: "Manager",
      role: "Manager",
      createdAt: new Date(2023, 0, 15),
      updatedAt: new Date(2023, 0, 16),
    },
    receiver: {
      id: 2,
      firstName: "Jane",
      lastName: "Smith",
      email: "jane.smith@example.com",
      password: "placeholderPassword",
      department: { id: 1, name: "General" },
      position: "Employee",
      role: "Employee",
      createdAt: new Date(2023, 1, 10),
      updatedAt: new Date(2023, 1, 13),
    },
    createdAt: new Date(2023, 2, 1),
    updatedAt: new Date(2023, 2, 2),
    forwardHistory: [],
    subject: "Subject 1",
    content: "Content of memo 1.",
    status: "unread",
    isRead: false,
    isForwarded: false
  },
  {
    id: "memo2",
    sentBy: {
      id: 3,
      firstName: "Alice",
      lastName: "Brown",
      email: "alice.brown@example.com",
      password: "placeholderPassword",
      department: { id: 1, name: "General" },
      position: "Admin",
      role: "Admin",
      createdAt: new Date(2023, 2, 15),
      updatedAt: new Date(2023, 2, 16),
    },
    receiver: {
      id: 4,
      firstName: "Bob",
      lastName: "Davis",
      email: "bob.davis@example.com",
      password: "placeholderPassword",
      department: { id: 1, name: "General" },
      position: "Employee",
      role: "Employee",
      createdAt: new Date(2023, 3, 12),
      updatedAt: new Date(2023, 3, 14),
    },
    createdAt: new Date(2023, 3, 1),
    updatedAt: new Date(2023, 3, 2),
    forwardHistory: [
      {
        from: {
          id: 5,
          firstName: "Carol",
          lastName: "Johnson",
          email: "carol.johnson@example.com",
          password: "placeholderPassword",
          department: { id: 1, name: "General" },
          position: "Administrator",
          role: "Administrator",
          createdAt: new Date(2023, 1, 5),
          updatedAt: new Date(2023, 1, 6),
        },
        to: {
          id: 6,
          firstName: "Eve",
          lastName: "Martinez",
          email: "eve.martinez@example.com",
          password: "placeholderPassword",
          department: { id: 1, name: "General" },
          position: "User",
          role: "User",
          createdAt: new Date(2023, 2, 7),
          updatedAt: new Date(2023, 2, 8),
        },
      },
    ],
    subject: "Subject 2",
    content: "Content of memo 2.",
    status: "read",
    isRead: true,
    isForwarded: true
  },
  {
    id: "memo3",
    sentBy: {
      id: 2,
      firstName: "Jane",
      lastName: "Smith",
      email: "jane.smith@example.com",
      password: "placeholderPassword",
      department: { id: 1, name: "General" },
      position: "Employee",
      role: "Employee",
      createdAt: new Date(2023, 1, 10),
      updatedAt: new Date(2023, 1, 13),
    },
    receiver: {
      id: 5,
      firstName: "Carol",
      lastName: "Johnson",
      email: "carol.johnson@example.com",
      password: "placeholderPassword",
      department: { id: 1, name: "General" },
      position: "Administrator",
      role: "Administrator",
      createdAt: new Date(2023, 1, 5),
      updatedAt: new Date(2023, 1, 6),
    },
    createdAt: new Date(2023, 3, 5),
    updatedAt: new Date(2023, 3, 7),
    forwardHistory: [],
    subject: "Subject 3",
    content: "Content of memo 3.",
    status: "unread",
    isRead: false,
    isForwarded: false
  },
  {
    id: "memo4",
    sentBy: {
      id: 1,
      firstName: "John",
      lastName: "Doe",
      email: "john.doe@example.com",
      password: "placeholderPassword",
      department: { id: 1, name: "General" },
      position: "Manager",
      role: "Manager",
      createdAt: new Date(2023, 0, 15),
      updatedAt: new Date(2023, 0, 16),
    },
    receiver: {
      id: 6,
      firstName: "Eve",
      lastName: "Martinez",
      email: "eve.martinez@example.com",
      password: "placeholderPassword",
      department: { id: 1, name: "General" },
      position: "User",
      role: "User",
      createdAt: new Date(2023, 2, 7),
      updatedAt: new Date(2023, 2, 8),
    },
    createdAt: new Date(2023, 3, 10),
    updatedAt: new Date(2023, 3, 12),
    forwardHistory: [],
    subject: "Subject 4",
    content: "Content of memo 4.",
    status: "read",
    isRead: true,
    isForwarded: false
  },
  {
    id: "memo5",
    sentBy: {
      id: 3,
      firstName: "Alice",
      lastName: "Brown",
      email: "alice.brown@example.com",
      password: "placeholderPassword",
      department: { id: 1, name: "General" },
      position: "Admin",
      role: "Admin",
      createdAt: new Date(2023, 2, 15),
      updatedAt: new Date(2023, 2, 16),
    },
    receiver: {
      id: 4,
      firstName: "Bob",
      lastName: "Davis",
      email: "bob.davis@example.com",
      password: "placeholderPassword",
      department: { id: 1, name: "General" },
      position: "Employee",
      role: "Employee",
      createdAt: new Date(2023, 3, 12),
      updatedAt: new Date(2023, 3, 14),
    },
    createdAt: new Date(2023, 3, 10),
    updatedAt: new Date(2023, 3, 11),
    forwardHistory: [],
    subject: "Subject 5",
    content: "Content of memo 5.",
    status: "unread",
    isRead: false,
    isForwarded: false
  },
  {
    id: "memo6",
    sentBy: {
      id: 1,
      firstName: "John",
      lastName: "Doe",
      email: "john.doe@example.com",
      password: "placeholderPassword",
      department: { id: 1, name: "General" },
      position: "Manager",
      role: "Manager",
      createdAt: new Date(2023, 0, 15),
      updatedAt: new Date(2023, 0, 16),
    },
    receiver: {
      id: 5,
      firstName: "Carol",
      lastName: "Johnson",
      email: "carol.johnson@example.com",
      password: "placeholderPassword",
      department: { id: 1, name: "General" },
      position: "Administrator",
      role: "Administrator",
      createdAt: new Date(2023, 1, 5),
      updatedAt: new Date(2023, 1, 6),
    },
    createdAt: new Date(2023, 3, 2),
    updatedAt: new Date(2023, 3, 2),
    forwardHistory: [
      {
        from: {
          id: 4,
          firstName: "Bob",
          lastName: "Davis",
          email: "bob.davis@example.com",
          password: "placeholderPassword",
          department: { id: 1, name: "General" },
          position: "Employee",
          role: "Employee",
          createdAt: new Date(2023, 3, 12),
          updatedAt: new Date(2023, 3, 14),
        },
        to: {
          id: 3,
          firstName: "Alice",
          lastName: "Brown",
          email: "alice.brown@example.com",
          password: "placeholderPassword",
          department: { id: 1, name: "General" },
          position: "Admin",
          role: "Admin",
          createdAt: new Date(2023, 2, 15),
          updatedAt: new Date(2023, 2, 16),
        },
      },
    ],
    subject: "Subject 6",
    content: "Content of memo 6.",
    status: "read",
    isRead: true,
    isForwarded: true
  },
  {
    id: "memo7",
    sentBy: {
      id: 2,
      firstName: "Jane",
      lastName: "Smith",
      email: "jane.smith@example.com",
      password: "placeholderPassword",
      department: { id: 1, name: "General" },
      position: "Employee",
      role: "Employee",
      createdAt: new Date(2023, 1, 10),
      updatedAt: new Date(2023, 1, 13),
    },
    receiver: {
      id: 4,
      firstName: "Bob",
      lastName: "Davis",
      email: "bob.davis@example.com",
      password: "placeholderPassword",
      department: { id: 1, name: "General" },
      position: "Employee",
      role: "Employee",
      createdAt: new Date(2023, 3, 12),
      updatedAt: new Date(2023, 3, 14),
    },
    createdAt: new Date(2023, 3, 16),
    updatedAt: new Date(2023, 3, 17),
    forwardHistory: [],
    subject: "Subject 7",
    content: "Content of memo 7.",
    status: "unread",
    isRead: false,
    isForwarded: false
  },
  {
    id: "memo8",
    sentBy: {
      id: 5,
      firstName: "Carol",
      lastName: "Johnson",
      email: "carol.johnson@example.com",
      password: "placeholderPassword",
      department: { id: 1, name: "General" },
      position: "Administrator",
      role: "Administrator",
      createdAt: new Date(2023, 1, 5),
      updatedAt: new Date(2023, 1, 6),
    },
    receiver: {
      id: 6,
      firstName: "Eve",
      lastName: "Martinez",
      email: "eve.martinez@example.com",
      password: "placeholderPassword",
      department: { id: 1, name: "General" },
      position: "User",
      role: "User",
      createdAt: new Date(2023, 2, 7),
      updatedAt: new Date(2023, 2, 8),
    },
    createdAt: new Date(2023, 3, 18),
    updatedAt: new Date(2023, 3, 19),
    forwardHistory: [],
    subject: "Subject 8",
    content: "Content of memo 8.",
    status: "read",
    isRead: true,
    isForwarded: false
  },
  {
    id: "memo9",
    sentBy: {
      id: 3,
      firstName: "Alice",
      lastName: "Brown",
      email: "alice.brown@example.com",
      password: "placeholderPassword",
      department: { id: 1, name: "General" },
      position: "Admin",
      role: "Admin",
      createdAt: new Date(2023, 2, 15),
      updatedAt: new Date(2023, 2, 16),
    },
    receiver: {
      id: 1,
      firstName: "John",
      lastName: "Doe",
      email: "john.doe@example.com",
      password: "placeholderPassword",
      department: { id: 1, name: "General" },
      position: "Manager",
      role: "Manager",
      createdAt: new Date(2023, 0, 15),
      updatedAt: new Date(2023, 0, 16),
    },
    createdAt: new Date(2023, 3, 20),
    updatedAt: new Date(2023, 3, 21),
    forwardHistory: [],
    subject: "Subject 9",
    content: "Content of memo 9.",
    status: "unread",
    isRead: false,
    isForwarded: false
  },
  {
    id: "memo10",
    sentBy: {
      id: 4,
      firstName: "Bob",
      lastName: "Davis",
      email: "bob.davis@example.com",
      password: "placeholderPassword",
      department: { id: 1, name: "General" },
      position: "Employee",
      role: "Employee",
      createdAt: new Date(2023, 3, 12),
      updatedAt: new Date(2023, 3, 14),
    },
    receiver: {
      id: 2,
      firstName: "Jane",
      lastName: "Smith",
      email: "jane.smith@example.com",
      password: "placeholderPassword",
      department: { id: 1, name: "General" },
      position: "Employee",
      role: "Employee",
      createdAt: new Date(2023, 1, 10),
      updatedAt: new Date(2023, 1, 13),
    },
    createdAt: new Date(2023, 3, 22),
    updatedAt: new Date(2023, 3, 23),
    forwardHistory: [
      {
        from: {
          id: 6,
          firstName: "Eve",
          lastName: "Martinez",
          email: "eve.martinez@example.com",
          password: "placeholderPassword",
          department: { id: 1, name: "General" },
          position: "User",
          role: "User",
          createdAt: new Date(2023, 2, 7),
          updatedAt: new Date(2023, 2, 8),
        },
        to: {
          id: 5,
          firstName: "Carol",
          lastName: "Johnson",
          email: "carol.johnson@example.com",
          password: "placeholderPassword",
          department: { id: 1, name: "General" },
          position: "Administrator",
          role: "Administrator",
          createdAt: new Date(2023, 1, 5),
          updatedAt: new Date(2023, 1, 6),
        },
      },
    ],
    subject: "Subject 10",
    content: "Content of memo 10.",
    status: "read",
    isRead: true,
    isForwarded: true
  },
];// Example usage:
// console.log(memoMockData);
